### PR TITLE
feat: add orchy

### PR DESCRIPTION
**Pull request by ilteoood**
## PR Checklist

- [X] I have read the [Contributing Guidelines on pull requests](https://github.com/italia-opensource/awesome-italia-opensource/blob/main/CONTRIBUTING.md#pull-requests).
- [X] I have read the [Code of conduct](https://github.com/italia-opensource/awesome-italia-opensource/blob/main/CODE_OF_CONDUCT.md).

**If this is an added new project**

- [X] I created the "project-name.json" file in the /data folder and complied with the required fields
- [X] The project you entered is still maintained and includes guidelines for use

**If this is related a issues/PR**

- [ ] I documented and tested the code

### CODE REVIEW

**Comment by FabrizioCafolla** [comment]
Hi, 

Sorry could you do an alignment with `main` because we fixed the error

**Comment by ilteoood** [comment]
@FabrizioCafolla done ☑

**Comment by FabrizioCafolla** [comment]
Hi, since I changed the repository logic you need to update the pr.

Just align from main branch and add the .json file inside the `awesome/opensource` folder

**Comment by ilteoood** [comment]
@FabrizioCafolla done ☑

**Pull request merged**
